// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xnxuqojzbfvlppsadwoa.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhueHVxb2p6YmZ2bHBwc2Fkd29hIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDE1MzY0NTQsImV4cCI6MjA1NzExMjQ1NH0.x8OqRcZKoOqS0V17j74Cu95PeEnnh9q0ubQCMTypnpI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);